version: '3'
services:
  couch:
    image: couchdb:1.7.1
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "couchdb"
      COUCHDB_PASSWORD: "password"
    volumes:
      - './data/couch:/usr/local/var/lib/couchdb'
    network_mode: host
  inventaire:
    build:
      context: ./.
      dockerfile: Dockerfile.inventaire
    ports:
      - "3006:3006"
    volumes:
      - ./inventaire:/opt/inventaire
    working_dir: /opt/inventaire
    network_mode: host
  elasticsearch:
    image: elasticsearch:2.4
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
    ports :
      - '127.0.0.1:9200:9200'
    volumes:
      # backup folder when ES container is removed
      - './data/es:/usr/share/elasticsearch/data'
    network_mode: host
  entities-search-engine:
    build:
      context: ./.
      dockerfile: Dockerfile.entities-search-engine
    command: 'node_modules/coffee-script/bin/coffee server/server.coffee'
    ports:
      - "3213:3213"
    volumes:
      - ./entities-search-engine:/opt/entities-search-engine
    working_dir: /opt/entities-search-engine
    network_mode: host
