version: '3'
services:
  couchdb:
    image: couchdb:3.4.2
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - 'couchdb:/opt/couchdb/data'
      - './configs:/opt/couchdb/etc/local.d'
      - './couchdb_debug.ini:/opt/couchdb/etc/local.ini'
      - './couchdbLog:/var/log/couchdb'
    tty: true
    #logging:
    #  driver: none
  elasticsearch:
    image: elasticsearch:7.16.2
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      # See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docker.html
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms500m -Xmx500m'
      - 'ingest.geoip.downloader.enabled=false'
    ports :
      - '9200:9200'
    volumes:
      - 'elasticsearch:/usr/share/elasticsearch/data'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  couchdb:
  elasticsearch:
