version: '3'
services:
  couchdb:
    image: couchdb:3.4.2
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "yourcouchdbusername"
      COUCHDB_PASSWORD: "yourcouchdbpassword"
    volumes:
      - 'couchdb:/opt/couchdb/data'
      - './configs:/opt/couchdb/etc/local.d'
    tty: true
  elasticsearch:
    image: elasticsearch:7.16.2
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      # See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docker.html
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    volumes:
      - 'elasticsearch:/usr/share/elasticsearch/data'
    ports :
      - '127.0.0.1:9200:9200'
volumes:
  couchdb:
  elasticsearch: