# Override `docker-compose.yml`. Use the -f option
# to specify the list of files. Compose merges files in the
# order they’re specified on the command line.
# See https://docs.docker.com/compose/extends
version: '3'
services:
  couchdb:
    volumes:
      - './data/couchdb-test:/usr/local/var/lib/couchdb'
  inventaire:
    ports: [ "3009:3009" ]
    environment:
      NODE_ENV: "tests-api"
