FROM node:8.12.0-jessie

RUN apt-get update \
  && apt-get install -y curl zsh git graphicsmagick inotify-tools \
  && apt-get clean

# Default to the same user as the host (override from command lin if needed)
# Known benefits:
# - allows to handle leveldb with level-party from both the host and container at the same time
USER 1000:1000

CMD ["npm", "start"]
